//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STOK_TAKİP_SON_HALİ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int UrunId { get; set; }
        public string ISBN { get; set; }
        public string KitapAdi { get; set; }
        public string YazarAdi { get; set; }
        public string Yayinevi { get; set; }
        public Nullable<int> YayinYili { get; set; }
        public string Dili { get; set; }
        public Nullable<double> Fiyat { get; set; }
        public string RafKodu { get; set; }
        public Nullable<int> KitapSayisi { get; set; }
    }
}
